version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "MyStrongPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1533:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql-scripts:/scripts
    networks:
      - app-network

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./sql-scripts:/scripts
    networks:
      - app-network
    entrypoint: >
      /bin/bash -c "
      echo 'Chờ SQL Server khởi động...';
      sleep 60;
      echo 'Tạo database EXE_PreOrder...';
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'MyStrongPassword123!' -Q \"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'EXE_PreOrder') CREATE DATABASE [EXE_PreOrder]\" ;
      echo 'Chạy script khởi tạo...';
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'MyStrongPassword123!' -d EXE_PreOrder -i /scripts/init.sql;
      echo 'Database đã được khởi tạo xong!';
      "

  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5190
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EXE_PreOrder;User Id=sa;Password=MyStrongPassword123!;TrustServerCertificate=True;
    ports:
      - "5190:5190"
    depends_on:
      - sql-init
    networks:
      - app-network

  redis:
    image: redis/redis-stack:latest
    container_name: eCommerce
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
